[tool.poetry]
name = ".dotfiles"
version = "0.1.0"
description = ""
authors = ["Nino Walker <nino.walker@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
ansible = "^4.6.0"
cookiecutter = "^1.7.3"
pip-tools = "^6.3.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
